# -*- coding: utf-8 -*-
"""Week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i63o7ww3uOTvHtqcEv5Fw3j1Ad77KKJE
"""

# Ask for the user's name
name = "Monday"
# Ask for the user's age
age = 25
# Ask the user is favarite language
favourite_language = "Python"
# Ask for the user's goal
goal = "President of South Sudan"

print(f"My name is {name}.")
print(f"I am {age} years old")
print(f"My favourite language is {favourite_language}")
print(f"My goal is to be {goal}")

