# -*- coding: utf-8 -*-
"""wek2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvDu9WRJuAcdIAtWGI8AAHFyxQEXwK7u
"""

# this a comment
# this is an integer expression
print(1 + 1)
# Create a variable that asks the user a bout the price of the energy drink
price = float(input("What is the price of energy drink in USD?"))
print(f"The price of energy drink is ${price}")

# Ask for the user's name
name = input("what is your name?")
# ask the user's goal
goal = input("What is your goal?")

# Ask for the price of the item
price = float(input("What is the price of the item?"))

# Ask for the quantity
quantity = int(input("How many do you want to buy?"))


# Calculate The total
total = price * quantity

# print the results
print(f"Your name is {name}.")
print(f"Your goal is {goal}.")
print(f"The price of one item is {price}.")
print(f"The quantity is {quantity}.")
print(f"The total cost is {total}")

print("---Simple Bill Calculator-----")
# Ask for the price of item
price = float(input("What is the price of item?"))
# Ask for the quantity
quantity = int(input("How many do you want to buy?"))

# Calculate the total
total = price * total

print(f"The price of one item is ${price}.")
print(f"The quantity is {quantity}.")
print(f"The total is ${total}")